<?php
/**
 * @file
 * Code for the blog_billet feature.
 */

include_once 'blog_billet.features.inc';

/**
 * Implements hook_menu.
 * @return array
 */
function blog_billet_menu(){
    $items = array();
    $items['billets'] = array(
        'title' => 'All billets',
        'page callback' => 'blog_billet_views',
        'access arguments' => array('view all articles'),
        'file' => 'include/blog_billet.view.inc',
    );

    return $items;
}

/**
 * Implements hook_permission
 * @return array
 */
function blog_billet_permission() {
    return array(
        'view all articles' => array(
            'title' => t('View articles'),
        ),
    );
}